### ISSUE TITLE
Create a  markdown file of 1 line and commit it in training repo

### ISSUE THREAD

**Issue by shallyarora** [shailendra735/training#1]

**Comment by rakesh-ranjan** [comment]
### This is first markdown..

MarkDown is _easy-to-read_ and **easy-to-write** plain text format. These will be converted in HTML while displaying on GITHUB.
The way to write **Ordered** and **Unordered List** ...
-HTML
-CSS
-JAVASCRIPT
1. HTML
2. CSS
3. JAVASCRIPT

This is the link for [GITHUB](https://github.com)

**Comment by SharadKumar** [comment]
@rakesh-auctionomy @zeba30

**Comment by shailendra735** [comment]
Completed!
